/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/alerts": {
    /**
     * Requires `alert:read`. Newest first. The raw event payload is omitted from list responses — it can
     * be large and nothing renders it here; GET /alerts/{id} carries it.
     *
     * An alert with `auto_quarantined: true` is one where the IDS moved the device into quarantine on its
     * own, through the same reclassification service a user's move goes through.
     */
    get: {
      parameters: {
        query: {
          /** Filter by severity */
          severity?: "info" | "low" | "medium" | "high" | "critical";
          /** Filter by device UUID */
          device_id?: string;
          /** Only events at or after this RFC3339 timestamp */
          since?: string;
          /** Filter by whether the alert has been acknowledged */
          acknowledged?: boolean;
          /** Page size (default 50, max 500) */
          limit?: number;
          /** Rows to skip (default 0) */
          offset?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-security-hub_internal_dto_Alert"];
        };
        /** invalid_severity or invalid_request */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/alerts/{id}": {
    /**
     * Requires `alert:read`. Unlike the list view, this includes `raw_payload` — the unparsed event as the
     * detection engine emitted it.
     */
    get: {
      parameters: {
        path: {
          /** Alert ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Alert"];
        };
        /** invalid_request */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** alert_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/alerts/{id}/acknowledge": {
    /**
     * Requires `alert:acknowledge`. Records who acknowledged it and when. Acknowledging an already
     * acknowledged alert is a 409 rather than a silent success, so two operators working the same queue can
     * tell that someone got there first.
     */
    post: {
      parameters: {
        path: {
          /** Alert ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["MessageResponse"];
        };
        /** invalid_request */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** alert_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
        /** already_acknowledged */
        409: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/alerts/{id}/false-positive": {
    /**
     * Requires `alert:false_positive`, which sits higher than plain acknowledgement: declaring a detection
     * wrong is a judgement about the ruleset, not just triage of one event.
     */
    post: {
      parameters: {
        path: {
          /** Alert ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["MessageResponse"];
        };
        /** invalid_request */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** alert_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/audit": {
    /**
     * Requires `audit:read`. Every security-relevant action produces a record: authentication, MFA,
     * credentials, authorization denials, user and session administration, network and policy changes,
     * detection triage and whole-appliance operations.
     *
     * The log is **append-only** — there is no update or delete endpoint — and hash-chained, so each entry
     * carries the previous entry's hash. `actor_username` is stored alongside the reference so history stays
     * readable after an account is deleted, and an action taken by the system itself has no actor.
     *
     * `details` never contains a password, hash, token, TOTP secret, recovery code or PSK: diffs are built
     * from a per-resource allow-list of fields rather than by reflecting over a struct.
     */
    get: {
      parameters: {
        query: {
          /** Filter by actor user UUID */
          actor?: string;
          /** Filter by action, e.g. device.classify */
          action?: string;
          /** Filter by resource type */
          resource_type?:
            | "device"
            | "vlan"
            | "firewall_rule"
            | "user"
            | "session";
          /** Filter by outcome */
          result?: "success" | "failure" | "denied";
          /** Only entries at or after this RFC3339 timestamp */
          from?: string;
          /** Only entries at or before this RFC3339 timestamp */
          to?: string;
          /** Page size (default 50, max 500) */
          limit?: number;
          /** Rows to skip (default 0) */
          offset?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-security-hub_internal_dto_AuditEntry"];
        };
        /** invalid_result or invalid_request */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/audit/verify": {
    /**
     * Requires `audit:read`. Walks the chain and reports the first inconsistent entry, so deleting or
     * editing any row is detectable rather than silent.
     *
     * A broken chain is a **200 with `valid: false`**, not an error status: reporting integrity is this
     * endpoint's job, and a 500 would conflate "the log has been tampered with", which is a finding, with
     * "verification could not run", which is a fault.
     */
    get: {
      responses: {
        /** valid, with broken_at_id when the chain is broken */
        200: {
          schema: definitions["VerifyAuditResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/auth/login": {
    /**
     * Unauthenticated. On success sets the httpOnly `sh_session` cookie and returns the CSRF token, so the
     * client can issue its first state-changing request without a further round trip.
     *
     * When the account has TOTP enrolled and no code was supplied, the response is **200** with
     * `mfa_required: true` and no cookie; the client resubmits all three fields. Every failure — unknown
     * username, wrong password, wrong code, locked or disabled account — returns the same
     * `401 invalid_credentials`, and the response time is padded to a constant floor, so neither the body nor
     * the timing discloses which one it was.
     *
     * Rate limited per IP: 10 attempts per minute and 60 per hour.
     */
    post: {
      parameters: {
        body: {
          /** Credentials, with the TOTP code when enrolled */
          request: definitions["LoginRequest"];
        };
      };
      responses: {
        /** Signed in, or mfa_required when a second factor is pending */
        200: {
          headers: {};
          schema: definitions["LoginResponse"];
        };
        /** invalid_credentials */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** rate_limited */
        429: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/auth/logout": {
    /**
     * Requires a session; no permission. The session row is marked revoked, never reused, and the cookie is
     * cleared in the same response.
     */
    post: {
      responses: {
        /** OK */
        200: {
          schema: definitions["MessageResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/auth/logout-all": {
    /** Requires a session; no permission. Signs the user out everywhere, including the calling client. */
    post: {
      responses: {
        /** OK */
        200: {
          schema: definitions["MessageResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/auth/mfa/confirm": {
    /**
     * Requires a session; no permission. Verifies a live code, activates MFA, rotates the session token, and
     * returns 10 single-use recovery codes.
     *
     * The codes are **shown exactly once**: only their Argon2id hashes are stored, so they cannot be
     * re-displayed. They are the offline recovery path — this appliance has no email-based reset and may have
     * no internet at all.
     */
    post: {
      parameters: {
        body: {
          /** A live TOTP code */
          request: definitions["MFAConfirmRequest"];
        };
      };
      responses: {
        /** Recovery codes, shown once */
        200: {
          schema: definitions["RecoveryCodesResponse"];
        };
        /** invalid_credentials or unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** mfa_already_enabled */
        409: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/auth/mfa/disable": {
    /**
     * Requires a session; no permission. Both factors are required: turning off a second factor is itself a
     * privileged act, so a stolen session alone cannot weaken the account. Outstanding recovery codes are
     * voided along with the secret.
     */
    post: {
      parameters: {
        body: {
          /** Password and a live TOTP code */
          request: definitions["MFADisableRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["MessageResponse"];
        };
        /** invalid_credentials or unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** mfa_not_enabled */
        409: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/auth/mfa/recovery-codes": {
    /**
     * Requires a session; no permission. Both factors are required. Issues 10 fresh single-use codes and
     * voids every previous one, so a set that may have been seen by someone else stops working immediately.
     * Like enrolment, the new codes are shown exactly once.
     */
    post: {
      parameters: {
        body: {
          /** Password and a live TOTP code */
          request: definitions["MFADisableRequest"];
        };
      };
      responses: {
        /** Fresh codes, shown once */
        200: {
          schema: definitions["RecoveryCodesResponse"];
        };
        /** invalid_credentials or unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** mfa_not_enabled */
        409: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/auth/mfa/setup": {
    /**
     * Requires a session; no permission. Returns the shared secret and an `otpauth://` URI for an
     * authenticator app. Enrolment is two-phase: MFA does **not** become active until
     * POST /auth/mfa/confirm verifies a live code, so a client that never finishes cannot lock the user out.
     * The secret is stored encrypted at rest with a device-local key.
     */
    post: {
      responses: {
        /** OK */
        200: {
          schema: definitions["MFASetupResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** mfa_already_enabled */
        409: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/auth/password": {
    /**
     * Requires a session; no permission. Verifies the current password, then revokes **all other** sessions
     * of this user and rotates the calling session's token — a privilege change never reuses a token.
     * The replacement cookie and a fresh CSRF token come back in the same response, so the caller stays
     * signed in while every other client is signed out.
     */
    post: {
      parameters: {
        body: {
          /** Current and new password */
          request: definitions["ChangePasswordRequest"];
        };
      };
      responses: {
        /** Carries the rotated CSRF token */
        200: {
          headers: {};
          schema: definitions["LoginResponse"];
        };
        /** weak_password or validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** invalid_credentials or unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/auth/password-policy": {
    /**
     * Unauthenticated: it is needed on the login and bootstrap screens, where no session exists.
     * Advisory only — the server enforces the policy regardless of what the client did with this.
     */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["PasswordPolicy"];
        };
      };
    };
  };
  "/auth/recovery": {
    /**
     * Unauthenticated by necessity — a user who cannot sign in cannot hold a session. This is the offline
     * recovery path: there is no email-based reset anywhere in this product, because the appliance may have
     * no internet.
     *
     * The code is single-use and is consumed whether or not the new password is accepted. Every failure
     * returns the same `401 invalid_credentials`. Rate limited per IP alongside /auth/login.
     */
    post: {
      parameters: {
        body: {
          /** Username, one recovery code and the new password */
          request: definitions["RecoveryRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["MessageResponse"];
        };
        /** weak_password or validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** invalid_credentials */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** rate_limited */
        429: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/auth/session": {
    /**
     * Requires a session; no permission. Returns the user, the resolved permission list and the CSRF token
     * for this session.
     *
     * The permission list is a **rendering hint only** — it exists so the UI can hide controls the user
     * cannot use. It is never authority: the server re-resolves permissions from the role on every request.
     */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["SessionResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/devices": {
    /**
     * Requires `device:read`. Soft-deleted devices are excluded. The current IP address is deliberately
     * not a field here — see GET /devices/{id}/leases.
     */
    get: {
      parameters: {
        query: {
          /** Filter by VLAN ID */
          vlan?: number;
          /** Filter by classification */
          classification?:
            | "quarantine"
            | "trusted"
            | "guest"
            | "cloud_native"
            | "cam"
            | "iot"
            | "services";
          /** Filter by whether the device is currently active */
          active?: boolean;
          /** Substring match on display name, vendor or model */
          search?: string;
          /** Page size (default 50, max 500) */
          limit?: number;
          /** Rows to skip (default 0) */
          offset?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-security-hub_internal_dto_Device"];
        };
        /** invalid_classification or invalid_request */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/devices/{id}": {
    /**
     * Requires `device:read`. Includes the device's known MAC addresses. `has_psk` reports whether a
     * credential is currently issued without disclosing its identifier, and the PSK secret itself is never
     * returned here — only POST /devices/{id}/psk/rotate ever shows one.
     */
    get: {
      parameters: {
        path: {
          /** Device UUID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Device"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
    /**
     * Requires `device:delete`. A **soft** delete: the row is retained so the audit trail and history view
     * still resolve it. The service additionally closes the current lease, ends open sessions, disables
     * device-scoped firewall rules and revokes the PSK, and hard-deletes the MAC rows so the same hardware
     * can be onboarded again without colliding on the unique index.
     */
    delete: {
      parameters: {
        path: {
          /** Device UUID */
          id: string;
        };
      };
      responses: {
        /** Deleted */
        204: never;
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
    /**
     * Requires `device:update`. Only the two user-authored fields are editable here; the VLAN and
     * classification move through POST /devices/{id}/classify, which is transactional.
     * Omitting a field leaves it alone; sending it empty clears it.
     */
    patch: {
      parameters: {
        path: {
          /** Device UUID */
          id: string;
        };
        body: {
          /** Fields to change */
          request: definitions["UpdateDeviceRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Device"];
        };
        /** validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/devices/{id}/alerts": {
    /**
     * Requires `alert:read` — the permission follows the data returned, not the device the path names.
     * The raw event payload is omitted here; GET /alerts/{id} carries it.
     */
    get: {
      parameters: {
        path: {
          /** Device UUID */
          id: string;
        };
        query: {
          /** Page size (default 50, max 500) */
          limit?: number;
          /** Rows to skip (default 0) */
          offset?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-security-hub_internal_dto_Alert"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/devices/{id}/classify": {
    /**
     * Requires `device:classify`. The core reclassification flow, executed as **one transaction**:
     * the device's VLAN and classification are updated, the current lease is closed and a new one issued in
     * the target segment, firewall rules are materialised from that VLAN's policy profile, hostapd is told
     * the PSK's new VLAN, the ruleset is applied, and an audit entry records the before and after VLAN.
     *
     * `classification` is optional: it is derived from the target VLAN when omitted, and must agree with it
     * when supplied. A VLAN that is reserved and not deployed is rejected with 409 rather than surfacing a
     * constraint error.
     *
     * Onboarding approval, quarantine release and automatic IDS quarantine all run this same service; they
     * differ only in who is recorded as the classifier.
     */
    post: {
      parameters: {
        path: {
          /** Device UUID */
          id: string;
        };
        body: {
          /** Target VLAN, and optionally the classification */
          request: definitions["ClassifyDeviceRequest"];
        };
      };
      responses: {
        /** What the move did: previous VLAN, new lease, rules applied, firewall generation */
        200: {
          schema: definitions["ClassifyResponse"];
        };
        /** classification_mismatch or validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found or vlan_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
        /** vlan_not_deployed or address_pool_exhausted */
        409: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/devices/{id}/domains": {
    /** Requires `dns:read` — the permission follows the data returned, not the device the path names. */
    get: {
      parameters: {
        path: {
          /** Device UUID */
          id: string;
        };
        query: {
          /** Page size (default 50, max 500) */
          limit?: number;
          /** Rows to skip (default 0) */
          offset?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-security-hub_internal_dto_DNSDomain"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/devices/{id}/fingerprints": {
    /**
     * Requires `device:read`. Passive identification signals — DHCP options 55 and 60, mDNS, SSDP, TLS JA4
     * and HTTP user agent — each with the confidence attached to it. This is what identifies hardware whose
     * MAC address is randomised.
     */
    get: {
      parameters: {
        path: {
          /** Device UUID */
          id: string;
        };
        query: {
          /** Page size (default 50, max 500) */
          limit?: number;
          /** Rows to skip (default 0) */
          offset?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-security-hub_internal_dto_Fingerprint"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/devices/{id}/internet-window": {
    /**
     * Requires `device:internet_window:grant`. Creates a device-scoped accept rule with an expiry and asks
     * the ipset layer for a matching timeout, so the database holds the intent while the kernel enforces the
     * expiry. Nothing sweeps expired rows: every read path filters on
     * `enabled AND (expires_at IS NULL OR expires_at > now)`.
     *
     * Bounded at 24 hours — a "timed" grant longer than a day is a permanent rule in disguise and should be
     * authored as one, so that it shows up in the deviation report. Requires an active lease to attach to.
     */
    post: {
      parameters: {
        path: {
          /** Device UUID */
          id: string;
        };
        body: {
          /** Window length in minutes (1–1440) */
          request: definitions["InternetWindowRequest"];
        };
      };
      responses: {
        /** The rule that was created, with its expiry */
        201: {
          schema: definitions["FirewallRule"];
        };
        /** validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
        /** no_active_lease */
        409: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
    /**
     * Requires `device:internet_window:grant`. Disables the window rule and drops the ipset entry rather
     * than waiting for the expiry.
     */
    delete: {
      parameters: {
        path: {
          /** Device UUID */
          id: string;
        };
      };
      responses: {
        /** Window revoked */
        204: never;
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/devices/{id}/leases": {
    /**
     * Requires `device:read`. Newest first. Exactly one lease carries `is_current: true` — that is the
     * device's address now. Reclassification closes the old lease and opens a new one, so the segment history
     * is readable here.
     */
    get: {
      parameters: {
        path: {
          /** Device UUID */
          id: string;
        };
        query: {
          /** Page size (default 50, max 500) */
          limit?: number;
          /** Rows to skip (default 0) */
          offset?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-security-hub_internal_dto_Lease"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/devices/{id}/psk": {
    /**
     * Requires `device:psk:revoke`. The device can no longer associate. Its credential row is retained in
     * the revoked state so the history stays readable, and the device's own PSK reference is cleared.
     */
    delete: {
      parameters: {
        path: {
          /** Device UUID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["MessageResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
        /** no_active_psk */
        409: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/devices/{id}/psk/rotate": {
    /**
     * Requires `device:psk:rotate`. Device identity is anchored to a per-device PSK rather than to a MAC
     * address, because MAC randomisation breaks MAC-anchored identity — rotating this key is therefore how a
     * device's credential is replaced, and the previous one is marked revoked.
     *
     * **This is the only response in the API that contains a live credential.** The key is shown exactly
     * once: nothing persists it and it never reaches a log or the audit trail, so it cannot be retrieved
     * again. If it is lost, rotate again.
     */
    post: {
      parameters: {
        path: {
          /** Device UUID */
          id: string;
        };
      };
      responses: {
        /** The new key, shown once */
        200: {
          schema: definitions["RotatePSKResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/devices/{id}/sessions": {
    /**
     * Requires `device:read`. 802.11 associations, newest first. An open session has no
     * `disconnected_at`; a closed one carries the 802.11 reason code where the radio reported it.
     */
    get: {
      parameters: {
        path: {
          /** Device UUID */
          id: string;
        };
        query: {
          /** Page size (default 50, max 500) */
          limit?: number;
          /** Rows to skip (default 0) */
          offset?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-security-hub_internal_dto_DeviceSession"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/devices/{id}/static-ip": {
    /**
     * Requires `device:static_ip:manage`. Creates a DHCP reservation. The address must lie inside the
     * device's current VLAN subnet and must not already be leased to another device.
     */
    put: {
      parameters: {
        path: {
          /** Device UUID */
          id: string;
        };
        body: {
          /** The address to reserve */
          request: definitions["StaticIPRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["MessageResponse"];
        };
        /** ip_outside_subnet or validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
        /** ip_in_use */
        409: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
    /** Requires `device:static_ip:manage`. The device returns to dynamic allocation from its VLAN's pool. */
    delete: {
      parameters: {
        path: {
          /** Device UUID */
          id: string;
        };
      };
      responses: {
        /** Reservation removed */
        204: never;
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/dns/domains": {
    /**
     * Requires `dns:read`. One row per device and domain, with a query count. `is_new` marks a domain seen
     * for the first time — an IoT device suddenly resolving something it never has before is exactly the
     * signal this view exists to surface.
     */
    get: {
      parameters: {
        query: {
          /** Filter by device UUID */
          device_id?: string;
          /** Filter by whether the domain is newly seen */
          is_new?: boolean;
          /** Filter by whether the domain is blocked */
          blocked?: boolean;
          /** Page size (default 50, max 500) */
          limit?: number;
          /** Rows to skip (default 0) */
          offset?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-security-hub_internal_dto_DNSDomain"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/dns/domains/{id}/block": {
    /** Requires `dns:block`. Resolution of the domain is refused for the device it was observed on. */
    post: {
      parameters: {
        path: {
          /** DNS domain record ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["MessageResponse"];
        };
        /** invalid_request */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** dns_domain_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
    /**
     * Requires `dns:block` — the same permission that blocks, since lifting a block and applying one are
     * the same authority over the same control.
     */
    delete: {
      parameters: {
        path: {
          /** DNS domain record ID */
          id: number;
        };
      };
      responses: {
        /** Unblocked */
        204: never;
        /** invalid_request */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** dns_domain_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/dns/domains/{id}/trust": {
    /**
     * Requires `dns:trust`. Marks the domain trusted and clears its "newly seen" flag, so it stops
     * appearing in the review queue.
     */
    post: {
      parameters: {
        path: {
          /** DNS domain record ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["MessageResponse"];
        };
        /** invalid_request */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** dns_domain_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/firewall/apply": {
    /**
     * Requires `firewall:apply`. Renders the active rules and installs them atomically, recording a numbered
     * generation with the ruleset it contained, so POST /firewall/rollback has something to return to.
     */
    post: {
      responses: {
        /** The generation that was installed */
        200: {
          schema: definitions["ApplyFirewallResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/firewall/deviations": {
    /**
     * Requires `firewall:read`. "Diverging from the preset" has three distinct meanings, so all three are
     * returned rather than one being picked:
     *
     * - `added` — active rules a user or the IDS wrote, with no preset behind them.
     * - `modified` — rules materialised from a preset whose priority, direction, protocol, port, zone, domain,
     * action or enabled flag no longer matches the template, with the differing fields named.
     * - `removed` — preset templates with no active materialised rule left.
     *
     * This is what lets the UI show an operator where the appliance has drifted from its declared policy.
     */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["DeviationsResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/firewall/preview": {
    /**
     * Requires `firewall:read`. Renders the active rules into a syntactically valid nftables ruleset. The
     * database is the source of truth and this text is the rendered artifact — never the other way around.
     *
     * Returned as `text/plain`, not JSON: it is a configuration artifact an operator may want to diff or
     * pipe to `nft -c`, and JSON escaping would make that awkward. Rendering does not install anything.
     */
    get: {
      responses: {
        /** The rendered nftables ruleset */
        200: {
          schema: string;
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/firewall/rollback": {
    /**
     * Requires `firewall:apply`. Reinstalls the ruleset recorded under the given generation. Not in the
     * original route list, but the renderer has always declared a rollback and the audit log has always had an
     * action for it — without a route neither was reachable.
     */
    post: {
      parameters: {
        body: {
          /** The generation to return to */
          request: definitions["RollbackRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["MessageResponse"];
        };
        /** validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** firewall_generation_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/firewall/rules": {
    /**
     * Requires `firewall:read`. By default only **active** rules are returned, meaning enabled and either
     * without an expiry or not yet expired. Nothing deletes expired rows — the kernel enforces expiry via
     * ipset timeouts while the database records intent — so `include_expired=true` is how the history is read.
     *
     * `origin` distinguishes a rule materialised from a profile preset, one a user wrote, and one the IDS
     * added automatically; the UI needs that distinction to show deviation from the preset.
     */
    get: {
      parameters: {
        query: {
          /** Filter by scope */
          scope?: "vlan" | "device";
          /** Filter by where the rule came from */
          origin?: "profile" | "user" | "ids_auto";
          /** Filter by VLAN */
          vlan_id?: number;
          /** Filter by device UUID */
          device_id?: string;
          /** Include disabled and expired rules (default false) */
          include_expired?: boolean;
          /** Page size (default 50, max 500) */
          limit?: number;
          /** Rows to skip (default 0) */
          offset?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-FirewallRule"];
        };
        /** invalid_scope, invalid_origin or invalid_request */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
    /**
     * Requires `firewall:rule:write`. The rule is always recorded with origin `user`; the field is not
     * accepted from the request, because a hand-written rule laundered into the preset would be invisible to
     * the deviation report.
     *
     * Scope decides which reference is required: a `vlan` rule needs `vlan_id`, a `device` rule needs
     * `device_id`. Writing a rule changes intent only — call POST /firewall/apply to install it.
     */
    post: {
      parameters: {
        body: {
          /** The rule to create */
          request: definitions["CreateFirewallRuleRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["FirewallRule"];
        };
        /** invalid_firewall_rule or validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** vlan_not_found or device_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/firewall/rules/{id}": {
    /**
     * Requires `firewall:rule:write`. A hard delete — the trail lives in the audit log, which is
     * append-only and hash-chained. Profile-derived rules are rejected with 409.
     */
    delete: {
      parameters: {
        path: {
          /** Firewall rule ID */
          id: number;
        };
      };
      responses: {
        /** Deleted */
        204: never;
        /** invalid_request */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** firewall_rule_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
        /** profile_rule_immutable */
        409: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
    /**
     * Requires `firewall:rule:write`. Profile-derived rules are rejected with 409: they are owned by their
     * policy profile, and editing one in place would make the preset and the enforced ruleset disagree with
     * no record of why. Edit the profile instead.
     *
     * Omitting a field leaves it alone. Clearing a nullable field is explicit — `clear_dst_port` and
     * `clear_expiry` — since a missing key and a null are indistinguishable once decoded.
     */
    patch: {
      parameters: {
        path: {
          /** Firewall rule ID */
          id: number;
        };
        body: {
          /** Fields to change */
          request: definitions["UpdateFirewallRuleRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["FirewallRule"];
        };
        /** invalid_firewall_rule or validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** firewall_rule_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
        /** profile_rule_immutable */
        409: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/onboarding/pending": {
    /**
     * Requires `onboarding:read`. There is no separate onboarding record: this is a projection over
     * devices, defined as active, undeleted devices in the quarantine VLAN that have never been classified.
     * That last condition is what separates a newly seen device from one the IDS put in quarantine, which
     * appears under GET /quarantine instead.
     */
    get: {
      parameters: {
        query: {
          /** Page size (default 50, max 500) */
          limit?: number;
          /** Rows to skip (default 0) */
          offset?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-security-hub_internal_dto_Device"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/onboarding/{id}/approve": {
    /**
     * Requires `onboarding:decide`. Runs the same reclassification transaction as
     * POST /devices/{id}/classify — the logic is not duplicated — and additionally sets the display name and
     * marks the device approved. `{id}` is the device UUID.
     */
    post: {
      parameters: {
        path: {
          /** Device UUID */
          id: string;
        };
        body: {
          /** Target VLAN and the label to give the device */
          request: definitions["ApproveOnboardingRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ClassifyResponse"];
        };
        /** validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found or vlan_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
        /** not_pending_onboarding or vlan_not_deployed */
        409: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/onboarding/{id}/reject": {
    /**
     * Requires `onboarding:decide`. Marks the device rejected and revokes its PSK, so it can no longer
     * associate and stops reappearing in the pending list. The device row is kept — rejection is recorded in
     * its own field rather than by deactivating the device, which the history view still needs.
     */
    post: {
      parameters: {
        path: {
          /** Device UUID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["MessageResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
        /** not_pending_onboarding */
        409: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/oui/lookup": {
    /**
     * Requires `device:read`. A MAC with the locally administered bit set is reported as
     * `randomized: true` and no lookup is attempted — there is no vendor behind a randomised address, and this
     * is why device identity is anchored to a PSK rather than to a MAC.
     *
     * Otherwise the registry is searched by longest prefix, 36 then 28 then 24 bits, so an MA-S or MA-M
     * assignment wins over the MA-L block that contains it. `found: false` means the address is a real vendor
     * address that is simply not in the local registry.
     *
     * The address may be given in any common separator form; it is normalised before lookup and returned
     * formatted.
     */
    get: {
      parameters: {
        query: {
          /** MAC address, e.g. aa:bb:cc:dd:ee:ff */
          mac: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["OUILookupResponse"];
        };
        /** invalid_mac or invalid_request */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/policy-profiles": {
    /**
     * Requires `policy:read`. A profile is a named set of rule templates; assigning one to a VLAN is what
     * makes reclassification materialise the right firewall rules. Built-in profiles cannot be deleted.
     * Unpaginated: the set is small.
     */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-security-hub_internal_dto_PolicyProfile"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/policy-profiles/{id}": {
    /** Requires `policy:read`. Includes the profile's rule templates. */
    get: {
      parameters: {
        path: {
          /** Policy profile ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["PolicyProfile"];
        };
        /** invalid_request */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** policy_profile_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/policy-profiles/{id}/rules": {
    /**
     * Requires `policy:read`. These are templates, not enforced rules: they are materialised into
     * firewall rules per VLAN, and each materialised rule points back at the template it came from, which is
     * what makes GET /firewall/deviations possible.
     */
    get: {
      parameters: {
        path: {
          /** Policy profile ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-PolicyRule"];
        };
        /** invalid_request */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** policy_profile_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/quarantine": {
    /**
     * Requires `quarantine:read`. Everything currently in the quarantine VLAN, whether it arrived there as
     * a new device or was isolated automatically by the IDS. Defined this way deliberately, so it does not
     * accidentally coincide with GET /onboarding/pending.
     */
    get: {
      parameters: {
        query: {
          /** Page size (default 50, max 500) */
          limit?: number;
          /** Rows to skip (default 0) */
          offset?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-security-hub_internal_dto_Device"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/quarantine/{device_id}/release": {
    /**
     * Requires `quarantine:release`. Runs the same reclassification transaction as
     * POST /devices/{id}/classify, recording the release in the audit log. The device must actually be in
     * quarantine.
     */
    post: {
      parameters: {
        path: {
          /** Device UUID */
          device_id: string;
        };
        body: {
          /** Segment to release the device into */
          request: definitions["ReleaseQuarantineRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ClassifyResponse"];
        };
        /** validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** device_not_found or vlan_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
        /** not_in_quarantine or vlan_not_deployed */
        409: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/roles": {
    /**
     * Requires a session; no permission. The mapping lives in code and is versioned with the source — it is
     * not editable at runtime. It is exposed read-only so the UI can render permission-aware controls, and
     * is a rendering hint rather than authority.
     */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["RoleMatrixResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
    /**
     * Requires `user:write`. Always returns **501**. Roles are static and defined in code, so there is
     * nothing to create; the route exists so that fact is explicit in this document rather than surfacing as
     * an undocumented 404.
     */
    post: {
      responses: {
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** not_implemented */
        501: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/sessions": {
    /**
     * Requires a session; no permission — a user may always see where they are signed in. The session
     * making the request is flagged `is_current`. Token hashes are never part of this representation.
     */
    get: {
      parameters: {
        query: {
          /** Page size (default 50, max 500) */
          limit?: number;
          /** Rows to skip (default 0) */
          offset?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-security-hub_internal_dto_Session"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/sessions/{id}": {
    /**
     * Revoking **your own** session needs no permission. Revoking someone else's requires
     * `session:revoke_any`.
     *
     * A session belonging to another user, when the caller lacks that permission, returns **404 rather than
     * 403** — a 403 would confirm the identifier exists and make session IDs enumerable.
     */
    delete: {
      parameters: {
        path: {
          /** Session UUID */
          id: string;
        };
      };
      responses: {
        /** Revoked */
        204: never;
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** session_not_found — also returned when the session belongs to someone else */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/setup/bootstrap": {
    /**
     * Unauthenticated, and usable exactly once. Requires the one-time setup token printed to stdout and the
     * system console at boot, so bootstrapping demands physical or serial access to the hub.
     * No default credentials exist; this is the only way an owner account is ever created.
     * Returns 409 setup_already_completed once an owner exists.
     */
    post: {
      parameters: {
        body: {
          /** Setup token and the owner's credentials */
          request: definitions["BootstrapRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["User"];
        };
        /** invalid_setup_token, weak_password or validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** setup_already_completed */
        409: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/setup/status": {
    /**
     * Unauthenticated. The one endpoint a client can always reach: it tells the UI whether to show the
     * bootstrap screen or the login screen.
     */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["SetupStatusResponse"];
        };
      };
    };
  };
  "/system/factory-reset": {
    /**
     * **Owner only**, and re-authenticated in the request body: possession of a live session is not enough
     * authority to wipe an appliance. Supply the current password, a TOTP code when enrolled, and
     * `confirm: "factory-reset"` — the literal operation name, so a misdirected click cannot do this.
     */
    post: {
      parameters: {
        body: {
          /** Password, TOTP code when enrolled, and confirm=factory-reset */
          request: definitions["ReauthRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["MessageResponse"];
        };
        /** confirmation_mismatch, totp_required or validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** invalid_credentials or unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/system/reboot": {
    /**
     * **Owner only**, re-authenticated in the request body exactly as the factory reset is. Supply the
     * current password, a TOTP code when enrolled, and `confirm: "reboot"`.
     */
    post: {
      parameters: {
        body: {
          /** Password, TOTP code when enrolled, and confirm=reboot */
          request: definitions["ReauthRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["MessageResponse"];
        };
        /** confirmation_mismatch, totp_required or validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** invalid_credentials or unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/system/status": {
    /**
     * Requires `system:read`. Aggregates the database, the detection and radio services, the headline
     * counts and the last applied firewall generation.
     *
     * A degraded subsystem is reported as a field rather than raised as an error: a status endpoint that
     * fails when something is wrong is useless exactly when it is needed.
     */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["SystemStatus"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/users": {
    /**
     * Requires `user:read`. No credential material appears in this representation at all — no hash, no
     * TOTP secret, no recovery codes. `is_locked` is derived rather than exposing the lockout expiry, which
     * would let a caller time the window precisely.
     */
    get: {
      parameters: {
        query: {
          /** Page size (default 50, max 500) */
          limit?: number;
          /** Rows to skip (default 0) */
          offset?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-User"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
    /**
     * Requires `user:write`, plus an explicit role check on top of it: an **admin may create only
     * operators and viewers**, never an owner or another admin. Escalation to one's own or a higher role is
     * refused regardless of permission bits.
     *
     * Every refusal returns the same generic 403, so a caller learns the action was refused rather than
     * which rule refused it — spelling out the boundary would map the authority model for them.
     */
    post: {
      parameters: {
        body: {
          /** The account to create */
          request: definitions["CreateUserRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["User"];
        };
        /** invalid_username, weak_password or validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** username_taken */
        409: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/users/{id}": {
    /** Requires `user:read`. */
    get: {
      parameters: {
        path: {
          /** User UUID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["User"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** user_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
    /**
     * Requires `user:delete` — **owner only**. A soft delete, with the username rewritten so it can be
     * claimed again: the unique index survives soft deletion, so leaving it in place would make the name
     * permanently unusable. History is unaffected, because the audit log stores the actor's username
     * alongside the reference and therefore outlives the account.
     *
     * You cannot delete your own account, and the last active owner cannot be deleted.
     */
    delete: {
      parameters: {
        path: {
          /** User UUID */
          id: string;
        };
      };
      responses: {
        /** Deleted */
        204: never;
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** user_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
        /** self_delete */
        409: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
    /**
     * Requires `user:write`, plus the same explicit role check as creation. Two further guards apply:
     * **nobody changes their own role**, and the **last active owner cannot be demoted** — an appliance with
     * no owner is permanently unadministrable, which is the same denial-of-service the auto-expiring account
     * lockout exists to avoid.
     *
     * Changing a role revokes that user's sessions, so the new authority takes effect immediately rather
     * than at their next sign-in.
     */
    patch: {
      parameters: {
        path: {
          /** User UUID */
          id: string;
        };
        body: {
          /** Fields to change */
          request: definitions["UpdateUserRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["User"];
        };
        /** validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** user_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/users/{id}/disable": {
    /**
     * Requires `user:write`, plus the role check. The account can no longer sign in and its sessions are
     * revoked immediately. The **last active owner cannot be disabled**.
     */
    post: {
      parameters: {
        path: {
          /** User UUID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["MessageResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** user_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/users/{id}/password-reset": {
    /**
     * Requires `user:write`, plus the role check. This is the administrator-driven half of account
     * recovery — there is no email-based reset in this product, because the appliance may have no internet.
     * The new password is marked as requiring a change at next sign-in, and the target's sessions are revoked.
     */
    post: {
      parameters: {
        path: {
          /** User UUID */
          id: string;
        };
        body: {
          /** The new password */
          request: definitions["ResetPasswordRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["MessageResponse"];
        };
        /** weak_password or validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** user_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/users/{id}/sessions": {
    /** Requires `session:read_all`. */
    get: {
      parameters: {
        path: {
          /** User UUID */
          id: string;
        };
        query: {
          /** Page size (default 50, max 500) */
          limit?: number;
          /** Rows to skip (default 0) */
          offset?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-security-hub_internal_dto_Session"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** user_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/vlans": {
    /**
     * Requires `vlan:read`. All eight segments, including VLAN 99, which is reserved and carries
     * `is_deployed: false` — devices cannot be placed in it. Unpaginated: the set is fixed and small.
     */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-security-hub_internal_dto_VLAN"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/vlans/{vid}": {
    /** Requires `vlan:read`. The VLAN ID matches the third octet of the segment's subnet. */
    get: {
      parameters: {
        path: {
          /** VLAN ID */
          vid: 5 | 10 | 20 | 30 | 40 | 50 | 60 | 99;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["VLAN"];
        };
        /** invalid_request */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** vlan_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
    /**
     * Requires `vlan:update`. The addressing scheme is fixed and not editable; what can change is the
     * label, client isolation and which policy profile the segment uses.
     *
     * A missing `policy_profile_id` and an explicit null are indistinguishable once decoded, so detaching a
     * profile is expressed by sending `detach_profile: true` rather than by sending a null.
     */
    patch: {
      parameters: {
        path: {
          /** VLAN ID */
          vid: number;
        };
        body: {
          /** Fields to change */
          request: definitions["UpdateVLANRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["VLAN"];
        };
        /** validation_failed or invalid_request */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** vlan_not_found or policy_profile_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/vlans/{vid}/devices": {
    /** Requires `device:read` — the permission follows the data returned, not the VLAN the path names. */
    get: {
      parameters: {
        path: {
          /** VLAN ID */
          vid: number;
        };
        query: {
          /** Page size (default 50, max 500) */
          limit?: number;
          /** Rows to skip (default 0) */
          offset?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ListResponse-security-hub_internal_dto_Device"];
        };
        /** invalid_request */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** vlan_not_found */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
  "/wifi/settings": {
    /**
     * Requires `wifi:read`. There is exactly one SSID by design: an SSID per VLAN would break the
     * reclassification flow, since a device would have to be reconfigured to move between segments. Segment
     * assignment comes from the device's PSK instead.
     */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["WiFiSettings"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** wifi_not_configured */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
    /**
     * Requires `wifi:update`. Omitting a field leaves it alone. Combinations that would weaken the radio
     * are rejected — notably requiring protected management frames while disabling them.
     */
    patch: {
      parameters: {
        body: {
          /** Fields to change */
          request: definitions["UpdateWiFiRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["WiFiSettings"];
        };
        /** invalid_wifi_settings or validation_failed */
        400: {
          schema: definitions["ErrorResponse"];
        };
        /** unauthenticated */
        401: {
          schema: definitions["ErrorResponse"];
        };
        /** permission_denied or csrf_token_invalid */
        403: {
          schema: definitions["ErrorResponse"];
        };
        /** wifi_not_configured */
        404: {
          schema: definitions["ErrorResponse"];
        };
      };
    };
  };
}

export interface definitions {
  Alert: {
    acknowledged?: boolean;
    acknowledged_at?: string;
    acknowledged_by?: string;
    auto_quarantined?: boolean;
    category?: string;
    device_id?: string;
    device_name?: string;
    dst_ip?: string;
    dst_port?: number;
    event_type?: string;
    id?: number;
    is_false_positive?: boolean;
    protocol?: string;
    raw_payload?: string;
    severity?: string;
    signature?: string;
    signature_id?: number;
    src_ip?: string;
    timestamp?: string;
  };
  ApplyFirewallResponse: {
    generation?: number;
  };
  ApproveOnboardingRequest: {
    display_name?: string;
    vlan_id: number;
  };
  AuditEntry: {
    action?: string;
    actor_role?: string;
    actor_user_id?: string;
    actor_username?: string;
    details?: string;
    hash?: string;
    id?: number;
    ip_address?: string;
    prev_hash?: string;
    resource_id?: string;
    resource_type?: string;
    result?: string;
    session_id?: string;
    timestamp?: string;
  };
  BootstrapRequest: {
    full_name?: string;
    password: string;
    setup_token: string;
    username: string;
  };
  ChangePasswordRequest: {
    current_password: string;
    new_password: string;
  };
  ClassifyDeviceRequest: {
    /**
     * @description Classification is optional: it is derived from the VLAN when omitted, and must agree with it
     * when supplied.
     * @enum {string}
     */
    classification?:
      | "quarantine"
      | "trusted"
      | "guest"
      | "cloud_native"
      | "cam"
      | "iot"
      | "services";
    vlan_id: number;
  };
  ClassifyResponse: {
    device?: definitions["Device"];
    firewall_generation?: number;
    new_lease_ip?: string;
    previous_vlan_id?: number;
    rules_applied?: number;
  };
  Counts: {
    active_devices?: number;
    devices?: number;
    firewall_rules?: number;
    quarantined?: number;
    unacknowledged_alerts?: number;
  };
  CreateFirewallRuleRequest: {
    /** @enum {string} */
    action: "accept" | "drop" | "reject";
    comment?: string;
    device_id?: string;
    /** @enum {string} */
    direction: "egress" | "ingress" | "inter_vlan";
    dst_domain?: string;
    dst_ip?: string;
    dst_port?: number;
    dst_zone?: string;
    priority?: number;
    /** @enum {string} */
    protocol?: "tcp" | "udp" | "icmp";
    /** @enum {string} */
    scope: "vlan" | "device";
    vlan_id?: number;
  };
  CreateUserRequest: {
    email?: string;
    full_name?: string;
    password: string;
    /** @enum {string} */
    role: "owner" | "admin" | "operator" | "viewer";
    username: string;
  };
  DNSDomain: {
    device_id?: string;
    domain?: string;
    first_seen?: string;
    id?: number;
    is_blocked?: boolean;
    is_new?: boolean;
    is_trusted?: boolean;
    last_seen?: string;
    query_count?: number;
  };
  DatabaseStatus: {
    ok?: boolean;
    path?: string;
    size_bytes?: number;
  };
  DeviationsResponse: {
    added?: definitions["FirewallRule"][];
    modified?: definitions["ModifiedRule"][];
    removed?: definitions["RemovedRule"][];
    total?: number;
  };
  Device: {
    classification?: string;
    classified_at?: string;
    classified_by?: string;
    display_name?: string;
    first_seen?: string;
    /**
     * @description HasPSK reports whether the device currently holds a credential, without disclosing its
     * identifier. The PSK secret is never exposed here; even the identifier is need-to-know.
     */
    has_psk?: boolean;
    id?: string;
    is_active?: boolean;
    last_seen?: string;
    macs?: definitions["DeviceMAC"][];
    model_name?: string;
    notes?: string;
    onboarding_state?: string;
    vendor_name?: string;
    vlan_id?: number;
    vlan_name?: string;
  };
  DeviceMAC: {
    first_seen?: string;
    is_randomized?: boolean;
    last_seen?: string;
    mac?: string;
    oui_vendor?: string;
  };
  DeviceSession: {
    connected_at?: string;
    disconnect_code?: number;
    disconnected_at?: string;
    id?: number;
    mac?: string;
    vlan_id?: number;
  };
  ErrorResponse: {
    error?: definitions["Payload"];
  };
  Fingerprint: {
    confidence?: number;
    id?: number;
    observed_at?: string;
    source?: string;
    value?: string;
  };
  FirewallRule: {
    action?: string;
    comment?: string;
    created_at?: string;
    device_id?: string;
    direction?: string;
    dst_domain?: string;
    dst_ip?: string;
    dst_port?: number;
    dst_zone?: string;
    enabled?: boolean;
    expires_at?: string;
    id?: number;
    origin?: string;
    origin_ref?: number;
    priority?: number;
    protocol?: string;
    scope?: string;
    vlan_id?: number;
  };
  FirewallStatus: {
    applied_at?: string;
    last_generation?: number;
  };
  InternetWindowRequest: {
    /**
     * @description Bounded at 24 hours: a "timed" grant longer than a day is a permanent rule wearing a
     * disguise, and should be authored as one so it shows up in the deviation report.
     */
    minutes: number;
  };
  Lease: {
    id?: number;
    ip_address?: string;
    is_current?: boolean;
    is_static?: boolean;
    lease_end?: string;
    lease_start?: string;
    mac?: string;
    vlan_id?: number;
  };
  "ListResponse-FirewallRule": {
    data?: definitions["FirewallRule"][];
    limit?: number;
    offset?: number;
    total?: number;
  };
  "ListResponse-PolicyRule": {
    data?: definitions["PolicyRule"][];
    limit?: number;
    offset?: number;
    total?: number;
  };
  "ListResponse-User": {
    data?: definitions["User"][];
    limit?: number;
    offset?: number;
    total?: number;
  };
  "ListResponse-security-hub_internal_dto_Alert": {
    data?: definitions["Alert"][];
    limit?: number;
    offset?: number;
    total?: number;
  };
  "ListResponse-security-hub_internal_dto_AuditEntry": {
    data?: definitions["AuditEntry"][];
    limit?: number;
    offset?: number;
    total?: number;
  };
  "ListResponse-security-hub_internal_dto_DNSDomain": {
    data?: definitions["DNSDomain"][];
    limit?: number;
    offset?: number;
    total?: number;
  };
  "ListResponse-security-hub_internal_dto_Device": {
    data?: definitions["Device"][];
    limit?: number;
    offset?: number;
    total?: number;
  };
  "ListResponse-security-hub_internal_dto_DeviceSession": {
    data?: definitions["DeviceSession"][];
    limit?: number;
    offset?: number;
    total?: number;
  };
  "ListResponse-security-hub_internal_dto_Fingerprint": {
    data?: definitions["Fingerprint"][];
    limit?: number;
    offset?: number;
    total?: number;
  };
  "ListResponse-security-hub_internal_dto_Lease": {
    data?: definitions["Lease"][];
    limit?: number;
    offset?: number;
    total?: number;
  };
  "ListResponse-security-hub_internal_dto_PolicyProfile": {
    data?: definitions["PolicyProfile"][];
    limit?: number;
    offset?: number;
    total?: number;
  };
  "ListResponse-security-hub_internal_dto_Session": {
    data?: definitions["Session"][];
    limit?: number;
    offset?: number;
    total?: number;
  };
  "ListResponse-security-hub_internal_dto_VLAN": {
    data?: definitions["VLAN"][];
    limit?: number;
    offset?: number;
    total?: number;
  };
  LoginRequest: {
    password: string;
    totp_code?: string;
    username: string;
  };
  LoginResponse: {
    csrf_token?: string;
    mfa_required?: boolean;
    must_change_password?: boolean;
    role?: string;
    user_id?: string;
    username?: string;
  };
  MFAConfirmRequest: {
    totp_code: string;
  };
  MFADisableRequest: {
    password: string;
    totp_code: string;
  };
  MFASetupResponse: {
    otpauth_uri?: string;
    secret?: string;
  };
  MessageResponse: {
    message?: string;
  };
  ModifiedRule: {
    changed_fields?: string[];
    policy_rule?: definitions["PolicyRule"];
    rule?: definitions["FirewallRule"];
  };
  OUILookupResponse: {
    found?: boolean;
    mac?: string;
    randomized?: boolean;
    vendor?: string;
  };
  PasswordPolicy: {
    common_passwords_count?: number;
    max_length?: number;
    min_length?: number;
    reject_common_passwords?: boolean;
    require_digit?: boolean;
    require_mixed_case?: boolean;
    require_symbol?: boolean;
  };
  Payload: {
    code?: string;
    fields?: { [key: string]: string };
    message?: string;
  };
  PolicyProfile: {
    description?: string;
    id?: number;
    is_builtin?: boolean;
    name?: string;
    rules?: definitions["PolicyRule"][];
  };
  PolicyRule: {
    action?: string;
    comment?: string;
    direction?: string;
    dst_domain?: string;
    dst_port?: number;
    dst_zone?: string;
    id?: number;
    priority?: number;
    protocol?: string;
  };
  ReauthRequest: {
    /** @description Confirm must be the literal resource name, so a misdirected click cannot wipe an appliance. */
    confirm: string;
    password: string;
    totp_code?: string;
  };
  RecoveryCodesResponse: {
    recovery_codes?: string[];
    warning?: string;
  };
  RecoveryRequest: {
    new_password: string;
    recovery_code: string;
    username: string;
  };
  ReleaseQuarantineRequest: {
    target_vlan_id: number;
  };
  RemovedRule: {
    policy_rule?: definitions["PolicyRule"];
    vlan_id?: number;
  };
  ResetPasswordRequest: {
    new_password: string;
  };
  RoleMatrixResponse: {
    roles?: { [key: string]: string[] };
  };
  RollbackRequest: {
    generation: number;
  };
  RotatePSKResponse: {
    psk?: string;
    warning?: string;
  };
  ServiceHealth: {
    enabled?: boolean;
    name?: string;
    running?: boolean;
    since?: string;
    version?: string;
  };
  ServicesStatus: {
    active_leases?: number;
    connected_stations?: number;
    dhcp_ok?: boolean;
    hostapd_ok?: boolean;
    suricata?: definitions["ServiceHealth"];
  };
  Session: {
    created_at?: string;
    expires_at?: string;
    id?: string;
    ip_address?: string;
    is_current?: boolean;
    last_active_at?: string;
    revoked_at?: string;
    user_agent?: string;
  };
  SessionResponse: {
    csrf_token?: string;
    email?: string;
    expires_at?: string;
    full_name?: string;
    mfa_enabled?: boolean;
    must_change_password?: boolean;
    permissions?: string[];
    role?: string;
    session_id?: string;
    user_id?: string;
    username?: string;
  };
  SetupStatusResponse: {
    setup_required?: boolean;
  };
  StaticIPRequest: {
    ip_address: string;
  };
  SystemStatus: {
    counts?: definitions["Counts"];
    database?: definitions["DatabaseStatus"];
    firewall?: definitions["FirewallStatus"];
    services?: definitions["ServicesStatus"];
    uptime_seconds?: number;
    version?: string;
  };
  UpdateDeviceRequest: {
    display_name?: string;
    notes?: string;
  };
  UpdateFirewallRuleRequest: {
    /** @enum {string} */
    action?: "accept" | "drop" | "reject";
    /** @description ClearDstPort and ClearExpiry make "set to null" explicit for the nullable columns. */
    clear_dst_port?: boolean;
    clear_expiry?: boolean;
    comment?: string;
    /** @enum {string} */
    direction?: "egress" | "ingress" | "inter_vlan";
    dst_domain?: string;
    dst_ip?: string;
    dst_port?: number;
    dst_zone?: string;
    enabled?: boolean;
    priority?: number;
    /** @enum {string} */
    protocol?: "tcp" | "udp" | "icmp";
  };
  UpdateUserRequest: {
    email?: string;
    full_name?: string;
    /** @enum {string} */
    role?: "owner" | "admin" | "operator" | "viewer";
  };
  UpdateVLANRequest: {
    client_isolation?: boolean;
    /**
     * @description DetachProfile makes "set to null" explicit, since a missing key and an explicit null are
     * indistinguishable once decoded into *uint.
     */
    detach_profile?: boolean;
    display_name?: string;
    policy_profile_id?: number;
  };
  UpdateWiFiRequest: {
    /** @enum {string} */
    band?: "2_4" | "5" | "dual";
    channel?: number;
    min_psk_entropy?: number;
    pmf_enabled?: boolean;
    pmf_required?: boolean;
    /** @enum {string} */
    security_mode?: "wpa2" | "wpa3" | "wpa2_wpa3_mixed";
    ssid?: string;
  };
  User: {
    created_at?: string;
    email?: string;
    full_name?: string;
    id?: string;
    /**
     * @description IsLocked is derived rather than exposing LockedUntil, which would let a caller time a
     * lockout window precisely.
     */
    is_locked?: boolean;
    last_login_at?: string;
    mfa_enabled?: boolean;
    must_change_password?: boolean;
    role?: string;
    status?: string;
    username?: string;
  };
  VLAN: {
    client_isolation?: boolean;
    dhcp_pool_end?: string;
    dhcp_pool_start?: string;
    display_name?: string;
    gateway_ip?: string;
    is_deployed?: boolean;
    name?: string;
    policy_profile?: string;
    policy_profile_id?: number;
    subnet_cidr?: string;
    vid?: number;
  };
  VerifyAuditResponse: {
    broken_at_id?: number;
    checked?: number;
    reason?: string;
    valid?: boolean;
  };
  WiFiSettings: {
    band?: string;
    channel?: number;
    min_psk_entropy?: number;
    pmf_enabled?: boolean;
    pmf_required?: boolean;
    security_mode?: string;
    ssid?: string;
    updated_at?: string;
  };
}

export interface operations {}

export interface external {}
